[package]
name = "bark"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", default-features = false, features = [
  "default-tls",
  "json"
] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
